### ISSUE TITLE
128x128

### ISSUE THREAD

**Issue by mahimabala1997** [wilhelmzeuschner/arduino_thermal_camera_with_sd_and_img_processing#1]
Hey! Thanks for the code that finally allows us to save images from the amg8833. I have a small request. Could you please guide me on how I can modify the code to work on a 1.44 inch Adafruit TFT display that does not have a touchscreen. How do I bring the image to 128x128 and not 320x240 because it doesn't fit on my screen

**Comment by wilhelmzeuschner** [comment]
Sorry that I totally missed your issue, unfortunately I didn't get notified :/
I assume that you know a little bit about electronics and the Arduino IDE.
The code uses the TFT_eSPI library: https://github.com/Bodmer/TFT_eSPI
The documentation describes what you have to change for different screens (in the User_setup.h file).
https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup.h
I think that you can get the code running pretty much unchanged (just with the correct screen selected for the display library).
Obviously, as you said, your screen's resolution is lower, but at least some parts of the image should be visible, that's a starting point.
I myself don't have a touch screen either on my LCD, so that part shouldn't be an issue.
Now to the code in `ThermalCameraMod_SD.ino`:
For all text elements you have to decide where you want them to be drawn, you have to change that, for your smaller screen you might want to omit some.
The void `DisplayGradient()` function contains the code that draws the array to the screen.
~line 547: 	`Display.fillRect((row * 3) + 15, (col * 3) + 15, BoxWidth, BoxHeight, GetColor(HDTemp[row][col]));`
This draws the individual colored segments. The first two arguments specify the starting x and y coordinates on the screen.
After that comes the width and height and finally the color. All you have to do is to find appropriate values for the `BoxWidth `and `BoxHeight `parameters and change the first (`(row * 3) + 15, (col * 3) + 15`) so that it fits with your smaller "pixels".
Some other UI elements like the frame around the image need to be changed too.
Since the interpolated array has a size of 70x70 and your display has only 128x128 pixels you can't scale up the array to twice the size on screen (which would mean 140x140. if you want you can either make the array smaller (rather complex changes to the code) or just not draw every "pixel" of your 70x70 array as a 2x2 pixel and make some of them overlap for example. That's just a thought, I belive that something similar is done in the current code too (line 518):
```
// fast way to draw a non-flicker grid--just make every 10 pixels 2x2 as opposed to 3x3
// drawing lines after the grid will just flicker too much
```

I hope this helps 
If you're able to get it running on this smaller screen, I'd love it if you could publish your modified code on your GitHub account. I'll definitely link to it.

**Comment by mahimabala1997** [comment]
This is a lot of help! Thanks for taking out your valuable time to guide me.
